
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderLink.Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"virgil_card\":{\"public_key\":{\"id\":\"70431d82-0327-4787-b430-b32634c59276\",\"create" +
            "d_at\":\"2016-02-04T13:37:31+02:00\",\"public_key\":\"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0t" +
            "LS0KTUlHYk1CUUdCeXFHU000OUFnRUdDU3NrQXdNQ0NBRUJEUU9CZ2dBRVhQV3p2KzFVNmdNUFFMSkpY" +
            "OGFOajRRMQpjMGJDK2h3c0lBWFJOclBnTThiVmZ1TXBQS25lNFZtdUpUS1VkU0djclR3dnJJTmlXUnE5" +
            "bWdzckd6ZTJBQ2RqCm1ZeklSZkM2RDBuU05XNjlNU01hNEt6bDZOemdmS09raWx6SVB4UUtqZmsrSGNJ" +
            "YWtndThUbElBZ1hvQlpSWFgKZk50V3N5cm9OTUYxRndkY0tDVT0KLS0tLS1FTkQgUFVCTElDIEtFWS0t" +
            "LS0tCg==\"},\"id\":\"ba179c74-622b-4702-a811-a5c771f018ba\",\"created_at\":\"2016-02-04T" +
            "13:37:31+02:00\",\"is_confirmed\":true,\"hash\":\"ek9k/J9UE2mFkFKX4IpgDZRy3DTY5qaKjPDL" +
            "PRd4YEtMTVUstzcqrHZ+jzzAq2cTuK2MYVWzTzJ27wdbdiMUdQ==\",\"identity\":{\"id\":\"6e39083f" +
            "-145f-463a-9e33-8dd9e04d1161\",\"created_at\":\"2016-02-04T13:37:31+02:00\",\"type\":0," +
            "\"value\":\"a166693@trbvn.com\",\"is_confirmed\":true},\"data\":{\"CreatedWith\":\"Virgil.D" +
            "isk\"}},\"private_key\":\"LS0tLS1CRUdJTiBFTkNSWVBURUQgUFJJVkFURSBLRVktLS0tLQpNSUlCS1" +
            "RBMEJnb3Foa2lHOXcwQkRBRURNQ1lFSUZmTlNZNkxoc0UzN0FVZm9JNkF0MHdQUXlqUXBaeWxiYlFICm" +
            "9zVkxYUy9kQWdJZ0FBU0I4TCsrK2R3bGcyR3NILzYrK2xvbVU0WjIwakQ0b2FvR091WEZKU25CTFpzYl" +
            "I4bVQKNkQrTXhBejkyS2JtV1VTQTI2dnMzVEwwZEtwSUI4SmRUUHEzQjdsd3dpajl5ZDBNWGlYODBJMn" +
            "dmR040cyt1OApGc1dnQ0VITk94OXAzNTJmSWFZZ09uZlUwZmNHd3hoWXArU2x2d21XeDNSVWJjZXczd1" +
            "dleTJiSUFDWGNiQXpsCjlUdUtRbnZGTU53b0VXUXJpdDl0WEJnVWVQOCtBQ3FtazJ2TGhxR0d6dUlCMj" +
            "BGTW9qK1ZEaXVZaVRYSThVWnIKd2VDWGVyY1k0VllKdGhveHZVUUlrKzVNV2VTRzl0WkczR3FYVk5EME" +
            "lBN3lrQyt0NC9EamNCWWJia1o5VnRRdApocDhkRldkbG5TU011UHJiWFE9PQotLS0tLUVORCBFTkNSWV" +
            "BURUQgUFJJVkFURSBLRVktLS0tLQo=\"}")]
        public string PersonalCard {
            get {
                return ((string)(this["PersonalCard"]));
            }
            set {
                this["PersonalCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public string PersonalCardPassword {
            get {
                return ((string)(this["PersonalCardPassword"]));
            }
            set {
                this["PersonalCardPassword"] = value;
            }
        }
    }
}